allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  '@tsparticles/engine': true
  '@vercel/speed-insights': true
  aws-crt: true
  aws-sdk: true
  esbuild: true
  prisma: true
  sharp: true
  unrs-resolver: true
