import {
  ArrowDown,
  ArrowRight,
  ArrowUp,
  ArrowUpDown,
  Biohazard,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsLeft,
  ChevronsRight,
  Clock,
  CreditCard,
  Download,
  Edit,
  EyeOff,
  Github,
  Laptop,
  LayoutDashboard,
  Link,
  Loader2,
  LogIn,
  LogOut,
  LucideIcon,
  Moon,
  Plus,
  PlusCircle,
  QrCode,
  Save,
  ScrollText,
  Settings,
  Settings2,
  Star,
  Sun,
  Trash,
  User,
  Wrench,
  X
} from 'lucide-react'

export type Icon = LucideIcon

export const Icons = {
  logo: Biohazard,
  sun: Sun,
  moon: Moon,
  laptop: Laptop,
  chevronLeft: ChevronLeft,
  arrowRight: ArrowRight,
  github: Github,
  login: LogIn,
  logout: LogOut,
  user: User,
  spinner: Loader2,
  settings: Settings,
  close: X,
  add: Plus,
  edit: Edit,
  save: Save,
  delete: Trash,
  download: Download,
  dashboard: LayoutDashboard,
  arrowUp: ArrowUp,
  arrowDown: ArrowDown,
  arrowUpDown: ArrowUpDown,
  eyeOff: EyeOff,
  plusCircle: PlusCircle,
  check: Check,
  chevronsLeft: ChevronsLeft,
  chevronsRight: ChevronsRight,
  chevronRight: ChevronRight,
  mixer: Settings2,
  card: CreditCard,
  qrCode: QrCode,
  wrench: Wrench,
  star: Star,
  link: Link,
  clock: Clock,
  note: ScrollText
}
